name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Target environment (test, uat, prod)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Tests
        uses: ./.github/actions/test

      - name: Build App
        uses: ./.github/actions/build
        with:
          environment: ${{ inputs.environment }}

      - name: Get BUILD_ENV from .env
        id: get-build-env
        run: |
          BUILD_ENV=$(grep "BUILD_ENV=" .env | cut -d '=' -f2 | tr -d '"' | tr -d "'")
          echo "build_env=$BUILD_ENV" >> $GITHUB_OUTPUT
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ steps.get-build-env.outputs.build_env }}
