name: Validate
on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run linter
        uses: ./.github/actions/lint
